spring:
  application:
    name: micro-weather-eureka-client-feign
    
server:
  port: 8086
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000