spring:
  application:
    name: micro-weather-eureka-client-zuul
    
server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
      
zuul:
  routes:
    hi: 
      path: /hi/**
      service-id: micro-weather-eureka-client