spring:
  application:
    name: micro-weather-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ron-Zheng/spring-cloud-weather-project
          search-paths:
          - config-repo

server:
  port: 8888

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
      